config/routes.rb
Rails.application.routes.draw do

  resources :glibraries
  # ORCID
  # Match is deprecated
  # match '/auth/:provider/callback' => 'authentications#orcid'
  # get '/auth/:provider/callback' => 'authentications#orcid'
  # post '/auth/:provider/callback' => 'authentications#orcid'
  # </ORCID>
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # from https://github.com/datacite/volpino/blob/master/config/routes.rb
  # devise_scope :user do
  #   get 'sign_in', :to => 'users/sessions#new', :as => :new_session
  #   post 'sign_in', :to => 'users/session#create', :as => :session
  #   get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  #
  #   get 'link_orcid', :to => 'users/sessions#link_orcid', :as => :link_orcid_session
  # end

  resources :experiments, :languages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "glibrary/index"
  get "experiments/index"
  # get "/home", :to => redirect('../public/home')
  get 'public/home'
  root "experiments#index"

end

app/models/experiment.rb
class Experiment < ApplicationRecord

end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  include  HTTParty
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  # GET /experiments
  # GET /experiments.json

  def index

      if $glibrary_response == nil
        puts "No token for gLibrary. Getting a glibrary token with " + ENV["GLIBRARY_USERNAME"].to_s
        Glibrary.get_token(ENV["GLIBRARY_USERNAME"],ENV["GLIBRARY_PASSWORD"])
        # The token is alive for two weeks.
        created = $glibrary_response['created']
        puts "token created at " + created.to_s
        token_created = Time.parse($glibrary_response['created']).to_i
        time_remaining = $token_expires - (Time.now.to_i)
      # token_created = DateTime.rfc3339($glibrary_response['created']).to_time.to_i
    elsif ($token_expires.to_i - Time.now.to_i < 100) || $token_expires == nil
        puts "the time remaining is less than 10 seconds - refreshing the token"
        Glibrary.get_token(ENV["GLIBRARY_USERNAME"],ENV["GLIBRARY_PASSWORD"])
        created = $glibrary_response['created']
        puts "token created at " + created.to_s + " and expires at " + $token_expires.to_s
      end

      puts "We have a token and TTL is still ok."
      p $token_expires.to_i - Time.now.to_i

      @experiments = Experiment.all
      @collections = Glibrary.collections

  end

  def collections(token)
    @collections = Glibrary.collections
  end
  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
    self.SaveToGlibrary
  end

  def SaveToGlibrary
    p  $glibrary_response
    post()
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:language, :primary, :configuration)
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for(experiment) do |f| %>
  <% if experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> <!--- if errors --->
<form role="form">
  <div class="field form-group">
    <!-- <label for="language">Please select which language you are working with</label>
    <input type="text_field" id="language" name="language" class="form-control" placeholder="Ent" /> -->
    <%= f.label :language %>
    <%= f.text_field :language, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <!-- <label for="primary">Is this experiment starting from a new definition, or are you forking an existing one ?</label>
    <input class="checkbox-inline" type="checkbox" id="primary" name="primary" class="form-control" /> -->
    <%= f.label :primary %><%= f.check_box :primary, class: 'form-control', type: 'checkbox-inline' %>
  </div>

  <div class="form-group">
    <!-- <label for="configuration">Experiment Configuration</label>
    <input type="textarea" id="configuration" name="configuration" class="form-control"/> -->
    <%= f.label :configuration %>
    <%= f.text_area :configuration, class: 'form-control' %>
  </div>

  <div class="form-actions">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>

<% end %>

app/views/experiments/edit.html.erb
<h1>Editing Experiment</h1>

<%= render 'form', experiment: @experiment %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% if user_signed_in? %><h2>Hello <%= current_user.name %>. Here are all the experiments.</h2>
<% else %><span class="label label-warning">You need to sign in to do anything</span><% end %>
<% if ($token_expires.to_i - Time.now.to_i < 100) %><span class="label-danger">You need a token.</span>
<% else %>
<span class="label label-success">glibrary: <span class="glyphicon glyphicon-ok-circle"></span> <span class="glyphicon glyphicon-refresh"></span>: <%= Time.at($token_expires).to_datetime
 %></span>
<% end %>

<div class="row">
  <div class="col-md-9">
    <h1>Experiments</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Language</th>
          <th>Primary</th>
          <th>Configuration</th>
          <th colspan="3"></th>
        </tr>
      </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.language %></td>
        <td><%= experiment.primary %></td>
        <td><%= experiment.configuration %></td>
        <td><%= link_to 'Show', experiment, {:class => 'btn' } %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment), {:class => 'btn btn-warning'} %></td>
        <td><%= link_to 'Destroy', experiment,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="col-md-1">
  <%= link_to 'New Experiment', new_experiment_path, {:class => 'btn btn-success'} %>
</div>
</div> <!-- row -->
<br>

app/views/experiments/new.html.erb
<h1>New Experiment</h1>

<%= render 'form', experiment: @experiment %>

<%= link_to 'Back', experiments_path , {:class => "btn btn-default-outline" }%>

app/views/experiments/show.html.erb
<div class="row">

<p id="notice"><%= notice %></p>

  <strong>Language:</strong>
  <%= @experiment.language %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @experiment.primary %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @experiment.configuration %>
</p>
</div>
<div class="row">
  <div class="col-sm-1">
<%= link_to 'Edit', edit_experiment_path(@experiment), {:class  =>'btn btn-warning'} %>
</div>
<div class='col-sm-2'>
<%= link_to 'Back', experiments_path, {:class => 'btn btn-default'} %>
</div>
</div>